services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    environment:
      GF_INSTALL_PLUGINS: 'grafana-llm-app'
      GF_AUTH_BASIC_ENABLED: true
      GF_AUTH_ANONYMOUS_ENABLED: false
      GF_SECURITY_ALLOW_EMBEDDING: true
      LLM_API_KEY: ${LLM_API_KEY:-}

  mcp-grafana:
    image: grafana/mcp-grafana
    ports:
      - 127.0.0.1:8001:8000/tcp
    environment:
      GRAFANA_URL: http://grafana:3000
      GRAFANA_USERNAME: admin
      GRAFANA_PASSWORD: admin
      PORT: 8001
    command: >
      -t streamable-http --log-level debug --disable-incident	--disable-oncall	--disable-sift	--disable-admin	--disable-asserts	--disable-annotations
    depends_on:
      - grafana

  alertmanager:
    image: grafana/mimir:2.16.0
    ports:
      - '127.0.0.1:8082:8080'
    command: --target=alertmanager --config.file=/etc/alertmanager/config.yml
    volumes:
      - ./provisioning/alertmanager/alertmanager.yml:/etc/alertmanager/config.yml

  # mcp-alertmanager:
  #   image: ghcr.io/ntk148v/alertmanager-mcp-server:sha-e9e2a1ea094b360ce299ac6ec828f70019584332
  #   ports:
  #     - 127.0.0.1:9090:8000/tcp
  #   environment:
  #     ALERTMANAGER_URL: http://alertmanager:8080/alertmanager
  #     MCP_PORT: 8000
  #     MCP_TRANSPORT: http
  #   depends_on:
  #     - grafana
  #     - alertmanager

  mcpo:
    image: ghcr.io/open-webui/mcpo
    ports:
      - 127.0.0.1:8000:8000/tcp
    volumes:
      - ./mcpo:/mcpo
    command: >
      --config /mcpo/config.json
    depends_on:
      - mcp-grafana

