services:
  grafana:
    user: root
    container_name: 'consensys-asko11y-app'

    build:
      context: .
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana}
        grafana_version: ${GRAFANA_VERSION:-12.3.1}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-false}
    ports:
      - 127.0.0.1:3000:3000/tcp
    volumes:
      - ../dist:/var/lib/grafana/plugins/consensys-asko11y-app
      - ../provisioning:/etc/grafana/provisioning
      - ..:/root/consensys-asko11y-app

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.consensys-asko11y-app:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: consensys-asko11y-app
