target: alertmanager
multitenancy_enabled: true
no_auth_tenant: anonymous
shutdown_delay: 0s
max_separate_metrics_groups_per_user: 1000
enable_go_runtime_metrics: false
api:
  skip_label_name_validation_header_enabled: false
  skip_label_count_validation_header_enabled: false
  alertmanager_http_prefix: /alertmanager
  prometheus_http_prefix: /prometheus
server:
  http_listen_network: tcp
  http_listen_address: ''
  http_listen_port: 8080
  http_listen_conn_limit: 0
  grpc_listen_network: tcp
  grpc_listen_address: ''
  grpc_listen_port: 9095
  grpc_listen_conn_limit: 0
  proxy_protocol_enabled: false
  tls_cipher_suites: ''
  tls_min_version: ''
  http_tls_config:
    cert: ''
    key: null
    client_ca: ''
    cert_file: ''
    key_file: ''
    client_auth_type: ''
    client_ca_file: ''
  grpc_tls_config:
    cert: ''
    key: null
    client_ca: ''
    cert_file: ''
    key_file: ''
    client_auth_type: ''
    client_ca_file: ''
  register_instrumentation: true
  report_grpc_codes_in_instrumentation_label_enabled: true
  graceful_shutdown_timeout: 30s
  http_server_read_timeout: 30s
  http_server_read_header_timeout: 0s
  http_server_write_timeout: 2m0s
  http_server_idle_timeout: 6m0s
  http_log_closed_connections_without_response_enabled: false
  grpc_server_max_recv_msg_size: 104857600
  grpc_server_max_send_msg_size: 104857600
  grpc_server_max_concurrent_streams: 1000
  grpc_server_max_connection_idle: 2562047h47m16.854775807s
  grpc_server_max_connection_age: 2562047h47m16.854775807s
  grpc_server_max_connection_age_grace: 2562047h47m16.854775807s
  grpc_server_keepalive_time: 2h0m0s
  grpc_server_keepalive_timeout: 20s
  grpc_server_min_time_between_pings: 10s
  grpc_server_ping_without_stream_allowed: true
  grpc_server_num_workers: 100
  grpc_server_stats_tracking_enabled: true
  grpc_server_recv_buffer_pools_enabled: false
  log_format: logfmt
  log_level: info
  log_source_ips_enabled: false
  log_source_ips_full: false
  log_source_ips_header: ''
  log_source_ips_regex: ''
  log_request_headers: false
  log_request_at_info_level_enabled: false
  log_request_exclude_headers_list: ''
  http_path_prefix: ''
  cluster_validation:
    label: ''
    grpc:
      enabled: false
      soft_validation: false
